@HostAddress = https://localhost:7078

### ユーザー登録
POST {{HostAddress}}/auth/register
Content-Type: application/json

{
  "email": "test@example1.com",
  "password": "Password123!"
}

### ログイン
POST {{HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123!"
}

### 外部ログイン
POST {{HostAddress}}/auth/external-login
Content-Type: application/json

{
  "email": "google_test@example.com",
  "name": "Google Test User",
  "provider": "Google",
  "providerKey": "google-provider-key-12345"
}

### メモ一覧取得
GET {{HostAddress}}/memo
Content-Type: application/json
Authorization: Bearer {上記で取得したJWT}
